### ISSUE TITLE
LaserScanSplit.msg does not fully follow ROS style guide

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_msgs#2]
the variable names within message definition should not be camelCase but lowercase_with_underscores.

also, rather than having single timestamp, i think it should use std_msgs/Header, which contains also frame_id in addition to time stamp

@Veix123 do you agree?

@mmaao how many files would be influenced by such correction?

**Comment by Veix123** [comment]
Yes I agree that variable names should follow ROS convention. Also std_msgs/Header makes sense, the variable name should then be called header instead of stamp.

**Comment by mmaao** [comment]
As far as I've seen, it's used by laserscan_to_distance.py which itself is used by teleop_with_laserscan.launch and all the gazebo launch files (there were 3 in the old repo).

**Comment by Veix123** [comment]
I suggest @mmaao updating all the hanging PR-s affected by this change and making a PR to this repository based on the discussion above.

**Comment by Veix123** [comment]
MIgrated to https://github.com/robotont/robotont_laserscan_to_distance.
